import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useState } from 'react'
import TikAPI from 'tikapi';


const inter = Inter({ subsets: ['latin'] })


function Home() {
  const [handle, setHandle] = useState('')

  const handleClick = async () => {
    // const data = fetch()
    console.log('fucking fuck')
  }

  const handleLogin = async () => { 
    console.log('fucking login')
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='mx-auto text-center'>
        <h1 className='text-3xl'>App</h1>
        <p className='text-xl'>Welcome to the app</p>
        <br/>
        <br/>

          <button type="button" onClick={handleLogin} className='bg-slate-400 rounded-xl p-2 mt-1' >Log the fuck in </button>

          <label>TikTok handle</label> <br/>
          <input type="text" className='bg-slate-200 border border-black rounded-xl py-1 px-2' onChange={(e) => setHandle(e.target.value)}/>
          <br/>
          <button type="button" onClick={handleClick} className='bg-slate-400 rounded-xl p-2 mt-1' >Get top keywords</button>



      </main>
    </>
  )
}

Home.getInitialProps = async () => {
  const api = TikAPI(process.env.NEXT_SERVER_TIKAPI);
  (async function(){
    try{
        let response = await api.public.check({
            username: "lilyachty"
        });
        console.log(response.json);
    }
    catch(err: any){
        console.log(err?.statusCode, err?.message, err?.json)
    }	
})();
  // return { stars: json.stargazers_count }
}

export default Home